[metadata]
name = pygorpmrustinfo
version = 0.1.3
author = Mike Moore
author_email = z_z_zebra@yahoo.com
license = MIT
description = Unified Go-backed helpers for rpmdb, rust audit, and Go build metadata
url = https://github.com/MikeMoore63/pygorpmrustinfo
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
zip_safe = False
setup_requires = setuptools-golang
scripts =
    get_go_info
    get_rpm_info
    get_rust_audit
package_dir =
    =src
packages = find:

[options.packages.find]
where = src

[options.entry_points]
pyinstaller40 =
  hook-dirs = pygorpmrustinfo._pyinstaller:get_hook_dirs
  tests     = pygorpmrustinfo._pyinstaller:get_PyInstaller_tests
